# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build, test and report coverage pipeline

on:
  workflow_dispatch:

  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: 📦 Build
        run: mvn --batch-mode --update-snapshots test jacoco:report --file pom.xml

      - name: 🚀 Report coverage
        run: mvn coveralls:report --define repoToken=${{ secrets.COVERALL_REPO_SECRET }}
